config/routes.rb
Rails.application.routes.draw do
  resources :shortened_urls
  get '/:some_short_code' => 'short_url#view'

  # You can have the root of your site routed with "root"
  root 'shortened_urls#new'
end

app/models/shortened_url.rb
class ShortenedUrl < ActiveRecord::Base
  SHORT_LENGTH = 8
  VALID_SHORT_CHARACTERS = "ABCDEFGHJKMNPQRSTWXY34679"
  VALIDATOR_REGEXP = /\A[#{VALID_SHORT_CHARACTERS}]+\z/i

  validates :long_url, format: { with: /\Ahttp.*/i, message: "must start with HTTP" }

  validates_uniqueness_of :short_url
  validates_length_of :short_url, in: SHORT_LENGTH..SHORT_LENGTH, message: "wrong length"
  validates :short_url, format: { with: VALIDATOR_REGEXP, message: "invalid characters" }

  before_validation :generate_short_url

  def generate_short_url
    self.short_url ||= VALID_SHORT_CHARACTERS.split('').sample(SHORT_LENGTH).join
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/short_url_controller.rb
class ShortUrlController < ApplicationController
  def view
    some_short_code = params[:some_short_code]
    short_url = ShortenedUrl.find_by_short_url(some_short_code)

    redirect_to short_url ? short_url.long_url : '/404'
  end
end

app/controllers/shortened_urls_controller.rb
class ShortenedUrlsController < ApplicationController
  before_action :set_shortened_url, only: [:show, :edit, :update, :destroy]

  # GET /shortened_urls
  # GET /shortened_urls.json
  def index
    @shortened_urls = ShortenedUrl.all
  end

  # GET /shortened_urls/1
  # GET /shortened_urls/1.json
  def show
  end

  # GET /shortened_urls/new
  def new
    @shortened_url = ShortenedUrl.new
  end

  # GET /shortened_urls/1/edit
  def edit
  end

  # POST /shortened_urls
  # POST /shortened_urls.json
  def create
    @shortened_url = ShortenedUrl.new(shortened_url_params)

    respond_to do |format|
      if @shortened_url.save
        format.html { redirect_to @shortened_url, notice: 'Shortened url was successfully created.' }
        format.json { render :show, status: :created, location: @shortened_url }
      else
        format.html { render :new }
        format.json { render json: @shortened_url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shortened_urls/1
  # PATCH/PUT /shortened_urls/1.json
  def update
    respond_to do |format|
      if @shortened_url.update(shortened_url_params)
        format.html { redirect_to @shortened_url, notice: 'Shortened url was successfully updated.' }
        format.json { render :show, status: :ok, location: @shortened_url }
      else
        format.html { render :edit }
        format.json { render json: @shortened_url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shortened_urls/1
  # DELETE /shortened_urls/1.json
  def destroy
    @shortened_url.destroy
    respond_to do |format|
      format.html { redirect_to shortened_urls_url, notice: 'Shortened url was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shortened_url
      @shortened_url = ShortenedUrl.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shortened_url_params
      params.require(:shortened_url).permit(:short_url, :long_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/short_url_helper.rb
module ShortUrlHelper
end

app/helpers/shortened_urls_helper.rb
module ShortenedUrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UrlShortener</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shortened_urls/_form.html.erb
<%= form_for(@shortened_url) do |f| %>
  <% if @shortened_url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shortened_url.errors.count, "error") %> prohibited this shortened_url from being saved:</h2>

      <ul>
      <% @shortened_url.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :long_url %> - starting with http <br>
    <%= f.text_field :long_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shortened_urls/edit.html.erb
<h1>Editing Shortened Url</h1>

<%= render 'form' %>

<%= link_to 'Show', @shortened_url %> |
<%= link_to 'Back', shortened_urls_path %>

app/views/shortened_urls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Shortened Urls</h1>

<table>
  <thead>
    <tr>
      <th>Short url</th>
      <th>Long url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shortened_urls.each do |shortened_url| %>
      <tr>
        <td><%= shortened_url.short_url %></td>
        <td><%= shortened_url.long_url %></td>
        <td><%= link_to 'Show', shortened_url %></td>
        <td><%= link_to 'Edit', edit_shortened_url_path(shortened_url) %></td>
        <td><%= link_to 'Destroy', shortened_url, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shortened url', new_shortened_url_path %>

app/views/shortened_urls/new.html.erb
<%= render 'form' %>

app/views/shortened_urls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  Short url:
  <strong><%= @shortened_url.short_url %></strong>
  will redirect to
  <strong><%= @shortened_url.long_url %></strong>
  (<%= link_to "TEST", "/" + @shortened_url.short_url, target: 'none' %> - opens in new tab)
</p>

<p>
  <a href="/">Create another short URL</a>
</p>